name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Linux,   os: ubuntu-latest }
        - { name: Windows, os: windows-latest }
        - { name: MacOS,   os: macos-latest }
    steps:
    - name: Get DirkSimple sources
      uses: actions/checkout@v4
    - name: Set up MSVC toolchain
      uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.platform.name == 'Windows' }}
      with:
        arch: x64
    - name: Set up ninja
      uses: ./.github/actions/setup-ninja
    - name: Set up SDL
      id: sdl
      uses: libsdl-org/setup-sdl@v1
      with:
        version: sdl3-latest
        cmake-generator: Ninja
    - name: Configure CMake
      run: cmake -B build -GNinja ${{ matrix.platform.flags }}
    - name: Build
      run: cmake --build build/
